require "pry"

# Class: DinnerClub
#
# Models a dinner club that includes a number of diners.
#
# Attributes:
# @members     - Array: contains string values for each member's name.
# @member_list - Hash: contains running check totals for diners.
#
# Public Methods:
# #member_list_init
# #event_go


class DinnerClub
  
  def initialize(members)
    @members = members
    @log = []
  end
  
  # Public: #member_list_init
  # Generates the member list hash with initial values of zero.
  #
  # Parameters:
  # none
  #
  # Returns:
  # @member_list: Hash
  #
  # State Changes:
  # Populates @member_list
  
  def member_list_init
    @member_list = {}
    @members.each { |m| @member_list[m] = 0 }
    @member_list
  end
  
  # Public: #event_go
  # Updates @member_list with member tabs for given event.
  #
  # Parameters:
  # eventobj - Event: object generated by Event class.
  #
  # Returns:
  # updated @member_list.
  #
  # State Changes:
  # Updates values in @member_list.
  
  def event_go(eventobj)
    event_check = CheckSplitter.new(eventobj.bill, eventobj.attendees.length)
    if eventobj.treat
      puts "Who is treating the Dinner Club?"
      treater = gets.chomp
      @member_list[treater] += event_check.total_bill
    else
      eventobj.attendees.each do |a| 
        @member_list[a] += event_check.per_person
      end
    end
    @log << eventobj
    @member_list
  end
  
end
    

# Class: Event
#
# Models an event attended by a Dinner Club.
#
# Attributes:
# @attendees    - Array: Members of dinner club attending event.
# @destination  - String: restaurant name where event is hosted.
# @bill         - Float: Bill for event for entire group.
# @treat        - Boolean: True if one member of the dinner club pays entire bill.
#
# Public Methods:
# none

class Event
  attr_reader :attendees
  attr_reader :destination
  attr_reader :bill
  attr_reader :treat
  
  def initialize(attendees, destination, bill, treat=false)
    @attendees = attendees
    @destination = destination
    @bill = bill
    @treat = treat
  end
  
  
end

# Class: CheckSplitter
#
# Given a single bill, calculates restaurant tab for member of large party including tip.
#
# Attributes:
# @bill       - Float: bill for entire group.
# @tip        - Integer: percent tip to leave. Default: 15.
# @party_size - Integer: number of people in the party.
#
# Public Methods:
# #total_bill
# #per_person

class CheckSplitter
  
  attr_reader :tip
  attr_reader :bill
  attr_reader :party_size
  
  def initialize(bill, tip=15, party_size)
    @bill = bill
    @tip = tip/100.0
    @party_size = party_size
  end
  
  # Public: #total_bill
  # Calculates the bill plus tip.
  #
  # Parameters:
  # bill - bill for entire group.
  # tip  - decimal tip number.
  #
  # Returns:
  # total_bill: bill including tip.
  #
  # State Changes:
  # None.
  
  def total_bill
    @bill + (@bill * @tip)
  end
  
  # Public: #per_person
  # Returns amount of tab for each member of dining party.
  #
  # Parameters:
  # total_bill - Return from total_bill method.
  # party_size - Integer: size of dining party.
  #
  # Returns:
  # Per_person: tab per party member.
  #
  # State Changes:
  # None.
  
  def per_person
    total_bill / @party_size
  end
  
  #def print_output
  #  puts "Total Bill: " + sprintf("%.2f", total_bill)
  #  puts "Per Person: " + sprintf("%.2f", per_person)
  #end
  
end

group = DinnerClub.new(["Sally","Mark","John","Claire","Jim","Sunny"])

party = Event.new(["Sally","Mark","John","Claire","Jim","Sunny"], "Granite City", 120.45)
huzzah = Event.new(["Mark","Claire","Sunny"], "Chili's", 36.8, true)
holiday = Event.new(["Sally","Mark","John","Jim","Sunny"], "Silverthorn", 346.4)


binding.pry